### ISSUE TITLE
Redesign of the landing page

### ISSUE THREAD

**Issue by Lenninlasd** [barranquillajs/bqjs#9]
Issues: 
- [x] Create social networks buttons on top of the page  https://github.com/barranquillajs/bqjs/issues/1
- [x] Create a UI component for the list of barranquillajs users https://github.com/barranquillajs/bqjs/issues/4
- [x] Create map of `Departamento del Atlántico` in d3 with node https://github.com/barranquillajs/bqjs/issues/2

Background: https://www.horchatajs.com/

![web 1920 1](https://user-images.githubusercontent.com/7197750/47455464-879c4880-d797-11e8-91d7-e1e330fa074a.png)
